### PR TITLE
Added "Magic Trackpad 3" to Device Support

### PR DESCRIPTION
**Pull request by NeariX67**
Just received my MT3 today and on the first few clicks it works fine.

EDIT: Bluetooth and USB work flawlessly. (Outside of regular problems like sensitivity)

### CODE REVIEW

**Comment by elton11220** [comment]
Great

**Comment by imbushuo** [comment]
Wow, they don't even change the device ID?

**Comment by jumpingbrowntrout** [comment]
What's the story with the Magic Track 3? I can't seem to find any info on it. How is it different from MT2?

**Comment by lloydo3000** [comment]
Different colour and braided USB cable

**Comment by jumpingbrowntrout** [comment]
Thanks @lloydo3000 so practically nothing! Here i thought i had MT2 all along but I have a braided cable so MT3 it is. There you go!

**Pull request merged**
