### PR TITLE
Introduce Bluetooth Magic Trackpad 2 support.

### LINKED ISSUE #128: Using driver for non apple computer+ Bluetooth magic trackpad?
Hi 

I'm interested in seeing what it takes to make the apple magic trackpad work for native windows computers with a bluetooth magic trackpad. Any suggestions? I have some CS background and would be interested in helping out.
Thanks.

### PR DESCRIPTION
**Pull request by imbushuo**
This resolves #128, #229, #299, #339, #374.

## Introduce Bluetooth support
Introduce Bluetooth support, it works fine now with some minor rough edges in the pairing routine. Probably I need to use the connectivity recovery timer a bit more to make it more resilient to various conditions.

## Introduce PTP Filter driver
Introduce the PTP filter driver, which will be the future home for all current driver implements. Eventually all drivers will be merged into the single one and others got removed. The PTP filter driver reuses Windows HID transportation stack to simplify our driver's logic, make transportation more resilient to system failure and reduces power consumption (especially helpful on laptops.)

Currently the PTP filter driver supports Magic Trackpad 2 via both USB and Bluetooth mode.

### CODE REVIEW

**Review by late-in-autumn — APPROVED** [review]
Remember to squash this PR.

**Comment by Jamesits** [comment]
LGTM

**Review by Jamesits — APPROVED** [review]

**Comment by shaipetel** [comment]
Awesome! I tried release 3965, does it have this in it?
It works perfectly with USB, but via Bluetooth it says can't use this driver.
Any specific installation steps for bluetooth?
I have unplugged the USB, searched for BT devices and paired with the trackpad.

Also - where can donations be sent to support this project?

**Comment by imbushuo** [comment]
It's not yet in release. Please wait for a few days.

Currently I have a full-time job that pays me enough so I turned donation off :)

**Comment by imbushuo** [comment]
FYI it's here: Release Release 3979 · imbushuo/mac-precision-touchpad (github.com)<https://github.com/imbushuo/mac-precision-touchpad/releases/tag/2105-3979>

---
Thanks,
Bingxing Wang
________________________________

**Comment by milesflavel** [comment]
It took a while to figure out that I had to completely remove the Apple driver, but everything is working great and my desk is slightly tidier
Have you got a paypal or ko-fi that I can send thanks to?

**Comment by o000u** [comment]
泪奔！！有生之年，终于等到你！！～～～

**Comment by Yarden92** [comment]
how do I get this version? 
I see it on release but when I do
choco install (or upgrade) mac-precision-touchpad
I end p with latest version of v0.2006.3826

Is there like a beta channel or something?

**Comment by imbushuo** [comment]
No. It’s on the release section, not sure why Choco doesn’t get updated.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
